import { createContext, useState } from "react";
import "./App.css";
import ReactDOM from "react-dom";
import { Routes, Route, BrowserRouter } from "react-router-dom";
import Home from "./pages/Home";
import ManPerfum from "./pages/ManPerfum";
import WomanPerfum from "./pages/WomanPerfum";
import Header from "./components/Header";
import Footer from "./components/Footer";
import SignIn from "./pages/SignIn";
import Cart from "./pages/Cart";
import Forgotpassword from "./pages/Forgotpassword";

export const AppContext = createContext(null);

function App() {
  const data = [
    {
      id: 1,
      brand: "Dolce & Gabbana",
      name: "Light BLue",
      price: "As low as 849,495.67(VND)",
      gender: "women's",
      sold: 1869,
      image: "https://img.fragrancex.com/images/products/sku/small/884w.jpg",
    },
    {
      id: 2,
      brand: "Dolce & Gabbana",
      name: "Light BLue",
      price: "As low as 619,276.01(VND)",
      gender: "men's",
      sold: 563,
      image: "https://img.fragrancex.com/images/products/sku/small/884m.webp",
    },
    {
      id: 3,
      brand: "Dolce & Gabbana",
      name: "The One",
      price: "As low as 867,028.16(VND)",
      gender: "men's",
      sold: 962,
      image: "https://img.fragrancex.com/images/products/sku/small/61199m.webp",
    },
    {
      id: 4,
      brand: "Dolce & Gabbana",
      name: "The One",
      price: "As low as 1,415,965.10(VND)",
      gender: "women's",
      sold: 579,
      image: "https://img.fragrancex.com/images/products/sku/small/61199w.webp",
    },
    {
      id: 5,
      brand: "Dolce & Gabbana",
      name: "Dolce & Gabbana",
      price: "As low as 957,821.91(VND)",
      gender: "men's",
      sold: 531,
      image: "https://img.fragrancex.com/images/products/sku/small/227m.webp",
    },
    {
      id: 6,
      brand: "Dolce & Gabbana",
      name: "K By Dolce & Gabbana ",
      price: "As low as 892,283(VND)",
      gender: "men's",
      sold: 106,
      image: "https://img.fragrancex.com/images/products/sku/small/77935m.webp",
    },
    {
      id: 7,
      brand: "Dolce & Gabbana",
      name: "Dolce & Gabbana Devotion",
      price: "As low as 2,496,309.46(VND)",
      gender: "women's",
      sold: 4,
      image: "https://img.fragrancex.com/images/products/sku/small/81565w.webp",
    },
    {
      id: 8,
      brand: "Dolce & Gabbana",
      name: "The Only One",
      price: "As low as 1,044,023.80(VND)",
      gender: "women's",
      sold: 82,
      image: "https://img.fragrancex.com/images/products/sku/small/61199m.webp",
    },
    {
      id: 9,
      brand: "Calvin Klein",
      name: "Eternity",
      price: "As low as 283,026.05(VND)",
      gender: "men's",
      sold: 965,
      image: "https://img.fragrancex.com/images/products/sku/small/352m.webp",
    },
    {
      id: 10,
      brand: "Calvin Klein",
      name: "Obsession",
      price: "As low as 194,528.22(VND)",
      gender: "men's",
      sold: 931,
      image: "https://img.fragrancex.com/images/products/sku/small/1002m.webp",
    },
    {
      id: 11,
      brand: "Calvin Klein",
      name: "Eternity Aqua",
      price: "As low as 477,554.27(VND)",
      gender: "men's",
      sold: 195,
      image: "https://img.fragrancex.com/images/products/sku/small/67088m.webp",
    },
    {
      id: 12,
      brand: "Calvin Klein",
      name: "Euphoria",
      price: "As low as (VND)",
      gender: "men's",
      sold: 195,
      image: "https://img.fragrancex.com/images/products/sku/small/60582m.webp",
    },
    {
      id: 13,
      brand: "Calvin Klein",
      name: "Eternity",
      price: "As low as 541,631.70(VND)",
      gender: "women's",
      sold: 1198,
      image: "https://img.fragrancex.com/images/products/sku/small/352w.webp",
    },
    {
      id: 14,
      brand: "Calvin Klein",
      name: "Escape",
      price: "As low as 690,032.52(VND)",
      gender: "women's",
      sold: 442,
      image: "	https://img.fragrancex.com/images/products/sku/small/345w.webp",
    },
    {
      id: 15,
      brand: "Calvin Klein",
      name: "Euphoria",
      price: "As low as 513,036.88(VND)",
      gender: "women's",
      sold: 1504,
      image: "https://img.fragrancex.com/images/products/sku/small/60582w.webp",
    },
    {
      id: 16,
      brand: "Calvin Klein",
      name: "Ck In 2u",
      price: "As low as 389,056.45(VND)",
      gender: "women's",
      sold: 211,
      image: "https://img.fragrancex.com/images/products/sku/small/75773w.webp",
    },
    {
      id: 17,
      brand: "Mont Blanc",
      name: "Montblanc Legend",
      price: "As low as 194,528.22(VND)",
      gender: "men's",
      sold: 593,
      image: "https://img.fragrancex.com/images/products/sku/small/69258m.webp",
    },
    {
      id: 18,
      brand: "Mont Blanc",
      name: "Montblanc Explorer",
      price: "As low as 247,543.43(VND)",
      gender: "men's",
      sold: 372,
      image: "https://img.fragrancex.com/images/products/sku/small/77021m.webp",
    },
    {
      id: 19,
      brand: "Mont Blanc",
      name: "Montblanc Legend Spirit",
      price: "As low as 208,512.55(VND)",
      gender: "men's",
      sold: 261,
      image: "https://img.fragrancex.com/images/products/sku/small/73486m.webp",
    },
    {
      id: 20,
      brand: "Mont Blanc",
      name: "Individuelle",
      price: "As low as 619,276.01(VND)",
      gender: "men's",
      sold: 394,
      image: "https://img.fragrancex.com/images/products/sku/small/1635m.webp",
    },
    {
      id: 21,
      brand: "Mont Blanc",
      name: "Montblanc Signature",
      price: "As low as 849,495.57(VND)",
      gender: "women's",
      sold: 34,
      image: "https://img.fragrancex.com/images/products/sku/small/80033w.webp",
    },
    {
      id: 22,
      brand: "Mont Blanc",
      name: "Presence",
      price: "As low as 499,887.44(VND)",
      gender: "women's",
      sold: 100,
      image: "https://img.fragrancex.com/images/products/sku/small/1078w.webp",
    },
    {
      id: 23,
      brand: "Mont Blanc",
      name: "Individuelle",
      price: "As low as 601,534.70(VND)",
      gender: "women's",
      sold: 85,
      image: "https://img.fragrancex.com/images/products/sku/small/1635w.webp",
    },
    {
      id: 24,
      brand: "Mont Blanc",
      name: "Lady Emblem",
      price: "As low as 760,997.75(VND)",
      gender: "women's",
      sold: 24,
      image: "https://img.fragrancex.com/images/products/sku/small/73202w.webp",
    },
    {
      id: 25,
      brand: "Christian Dior",
      name: "Sauvage",
      price: "As low as 1,061,765.11(VND)",
      gender: "men's",
      sold: 496,
      image: "https://img.fragrancex.com/images/products/sku/small/73223m.webp",
    },
    {
      id: 26,
      brand: "Christian Dior",
      name: "Dior Homme Intense",
      price: "As low as 2,489,001.15(VND)",
      gender: "men's",
      sold: 168,
      image: "https://img.fragrancex.com/images/products/sku/small/70018m.webp",
    },
    {
      id: 27,
      brand: "Christian Dior",
      name: "Farenheit",
      price: "As low as 1,549,775.44(VND)",
      gender: "men's",
      sold: 302,
      image: "https://img.fragrancex.com/images/products/sku/small/372m.webp",
    },
    {
      id: 28,
      brand: "Christian Dior",
      name: "Eau Sauvage",
      price: "As low as 831,336.82(VND)",
      gender: "men's",
      sold: 115,
      image: "https://img.fragrancex.com/images/products/sku/small/291m.webp",
    },
    {
      id: 29,
      brand: "Christian Dior",
      name: "Jadore",
      price: "As low as 743,882.61(VND)",
      gender: "women's",
      sold: 390,
      image: "https://img.fragrancex.com/images/products/sku/small/553w.webp",
    },
    {
      id: 30,
      brand: "Christian Dior",
      name: "Hypnotic Poison",
      price: "As low as 1,690,642.29(VND)",
      gender: "women's",
      sold: 260,
      image: "https://img.fragrancex.com/images/products/sku/small/518w.webp",
    },
    {
      id: 31,
      brand: "Christian Dior",
      name: "Miss Dior",
      price: "As low as 1,424,522.68(VND)",
      gender: "women's",
      sold: 186,
      image: "https://img.fragrancex.com/images/products/sku/small/60587w.webp",
    },
    {
      id: 32,
      brand: "Christian Dior",
      name: "Poison",
      price: "As low as 2,107,041.23(VND)",
      gender: "women's",
      sold: 173,
      image: "https://img.fragrancex.com/images/products/sku/small/1064w.webp",
    },
    {
      id: 33,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Man Blue",
      price: "As low as 600,073.65(VND)",
      gender: "men's",
      sold: 113,
      image: "https://img.fragrancex.com/images/products/sku/small/76480m.webp",
    },
    {
      id: 34,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Ice",
      price: "As low as 530,778.19(VND)",
      gender: "men's",
      sold: 103,
      image: "https://img.fragrancex.com/images/products/sku/small/74503m.webp",
    },
    {
      id: 35,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Man Intense",
      price: "As low as 991,008.59(VND)",
      gender: "men's",
      sold: 118,
      image: "https://img.fragrancex.com/images/products/sku/small/73796m.webp",
    },
    {
      id: 36,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Urban Hero",
      price: "As low as 566,052.09(VND)",
      gender: "men's",
      sold: 40,
      image: "https://img.fragrancex.com/images/products/sku/small/78359m.webp",
    },
    {
      id: 37,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Bolossom",
      price: "As low as 270,294.04(VND)",
      gender: "women's",
      sold: 186,
      image: "https://img.fragrancex.com/images/products/sku/small/72121w.webp",
    },
    {
      id: 38,
      brand: "Jimmy Choo",
      name: "JImmy Choo",
      price: "As low as 229,802.12(VND)",
      gender: "women's",
      sold: 758,
      image: "https://img.fragrancex.com/images/products/sku/small/67930w.webp",
    },
    {
      id: 39,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Fever",
      price: "As low as 579,201.53(VND)",
      gender: "women's",
      sold: 200,
      image: "https://img.fragrancex.com/images/products/sku/small/76670w.webp",
    },
    {
      id: 40,
      brand: "Jimmy Choo",
      name: "Jimmy Choo Illicit",
      price: "As low as 62,407.66(VND)",
      gender: "women's",
      sold: 167,
      image: "https://img.fragrancex.com/images/products/sku/small/73473w.webp",
    },
    {
      id: 41,
      brand: "Versace",
      name: "Versace Eros",
      price: "As low as 176,786.92(VND)",
      gender: "men's",
      sold: 951,
      image: "https://img.fragrancex.com/images/products/sku/small/69867m.webp",
    },
    {
      id: 42,
      brand: "Versace",
      name: "Versace Man",
      price: "As low as 159,045.61(VND)",
      gender: "men's",
      sold: 801,
      image: "https://img.fragrancex.com/images/products/sku/small/1680m.webp",
    },
    {
      id: 43,
      brand: "Versace",
      name: "Versace Pour Homme Dylan Blue",
      price: "As low as 194,528.22(VND)",
      gender: "men's",
      sold: 472,
      image: "https://img.fragrancex.com/images/products/sku/small/73732m.webp",
    },
    {
      id: 44,
      brand: "Versace",
      name: "Versace Pour Homme",
      price: "As low as 194,528.22(VND)",
      gender: "men's",
      sold: 708,
      image: "https://img.fragrancex.com/images/products/sku/small/64213m.webp",
    },
    {
      id: 45,
      brand: "Versace",
      name: "Bright Crystal",
      price: "As low as 490,703.71(VND)",
      gender: "women's",
      sold: 1146,
      image: "https://img.fragrancex.com/images/products/sku/small/61100w.webp",
    },
    {
      id: 46,
      brand: "Versace",
      name: "Crystal Noir",
      price: "As low as 207,677.66(VND)",
      gender: "women's",
      sold: 702,
      image: "https://img.fragrancex.com/images/products/sku/small/60546w.webp",
    },
    {
      id: 47,
      brand: "Versace",
      name: "Versace Yellow Diamond",
      price: "As low as 270,294.04(VND)",
      gender: "women's",
      sold: 369,
      image: "https://img.fragrancex.com/images/products/sku/small/69189w.webp",
    },
    {
      id: 48,
      brand: "Versace",
      name: "Versace Woman",
      price: "As low as 548,519.50(VND)",
      gender: "women's",
      sold: 159,
      image: "https://img.fragrancex.com/images/products/sku/small/1321w.webp",
    },
  ];
  return (
    <AppContext.Provider value={{ dataKey: data }}>
      <BrowserRouter>
        <Header />
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/men" element={<ManPerfum />} />
          <Route path="/women" element={<WomanPerfum />} />
          <Route path="/sign" element={<SignIn />} />
          <Route path="/cart" element={<Cart />} />
          <Route path="/forgotpassword" element={<Forgotpassword />} />
        </Routes>
        <Footer />
      </BrowserRouter>
    </AppContext.Provider>
  );
}

export default App;
